notifcations:
  email:
    - me@rogerignazio.com
rvm:
    - 1.9.3
    - 1.8.7
env:
  - PUPPET_VERSION=2.7.23
  - PUPPET_VERSION=3.1.0
  - PUPPET_VERSION=3.2.1
matrix:
    exclude:
        - {rvm: 1.9.3, env: PUPPET_VERSION=2.7.23}
